- name: Create Azure Resource Group
  hosts: controller
  gather_facts: False
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ rg_name }}"
        location: "{{ location }}"
      register: output
