- name: Create vars file
  hosts: controller
  gather_facts: False
  tasks:
    - name: Inserting variables into vars.yaml
      blockinfile:
        path: $HOME/vars.yaml
        block: |
          rg_name: "{{ pg_name }}"
          location: "{{ location }}"
