- name: Create vars file
  hosts: controller
  tasks:
    - name: Creating a vars file
      file:
        path: "$HOME/{{ pg_name }}.yaml"
        state: touch

    - name: Inserting variables into vars.yaml
      blockinfile:
        path: $HOME/{{ pg_name }}.yaml
        block: |
          rg_name: "{{ pg_name }}"
          location: "{{ location }}"

    - name: Create RG
      command: ansible-playbook createrg.yaml -e @"{{ pg_name }}".yaml
