- name: Create vars file
  hosts: controller
  tasks:

    - name: Inserting variables into vars.yaml
      copy:
        dest: "$HOME/{{ pg_name }}.yaml"
        content: |
          rg_name: "{{ pg_name }}"
          location: "{{ location }}"

    - name: Create RG
      command: ansible-playbook createrg.yaml -e @"{{ pg_name }}".yaml
