- name: Create vars file
  hosts: controller
  gather_facts: False
  tasks:
    - name: Inserting variables into vars.yaml
      shell: ifconfig
      register: output
     
    - debug:
       msg: output
