- name: Create vars file
  hosts: controller
  gather_facts: False
  tasks:
    - name: Creating a vars file
      file: 
        path: $HOME/{{ pg_name }}.yaml
        state: touch

    - name: Inserting variables into vars.yaml
      blockinfile:
        path: $HOME/{{ pg_name }}.yaml
        block: |
          rg_name: {{ pg_name }}
          location: {{ location }}
          
    - name: Creating RG
      command: ansible-playbook createrg.yaml -e @{{ pg_name }}.yaml
      
    - name: Move to vars archive folder
      command: mv $HOME/{{ pg_name }}.yaml $HOME/vars_archive/
